version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet
  backend:
    build:
      context: ./backend
    ports:
      - '8080:8080'
    networks:
      - webnet
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    networks:
      - webnet
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - '8081:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - webnet
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  pgdata: {}
  pgadmin-data: {}
networks:
  webnet:
    driver: bridge
